# Generated by Django 4.2.13 on 2024-06-19 20:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_comment_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('user', 'post', 'comment')},
        ),
    ]
